// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfp_uD0rGjKZFOUKEF0r-9Ifw9ptUhk8',
    appId: '1:376094719148:web:6d71b34f24e6deb9913309',
    messagingSenderId: '376094719148',
    projectId: 'flutterfireku',
    authDomain: 'flutterfireku.firebaseapp.com',
    storageBucket: 'flutterfireku.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YZVk94p4eqxvx_2LxtTscuYFD9uL4Sg',
    appId: '1:376094719148:android:591947d650c311be913309',
    messagingSenderId: '376094719148',
    projectId: 'flutterfireku',
    storageBucket: 'flutterfireku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQb4-WjK06A2qHPraPyPOkyf4FwhtBKJE',
    appId: '1:376094719148:ios:d00739350a870c88913309',
    messagingSenderId: '376094719148',
    projectId: 'flutterfireku',
    storageBucket: 'flutterfireku.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQb4-WjK06A2qHPraPyPOkyf4FwhtBKJE',
    appId: '1:376094719148:ios:1890af4c372295de913309',
    messagingSenderId: '376094719148',
    projectId: 'flutterfireku',
    storageBucket: 'flutterfireku.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
